name: whatinsearching
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - apscheduler>=3.10.4
  - pytz>=2023.3.post1
  - requests>=2.31.0
  - urllib3>=2.1.0
  - streamlit>=1.28.2
  - tiktoken>=0.5.2
  - openai>=1.2.0
  - matplotlib>=3.8.2
  - seaborn>=0.13.0
  - pandas>=2.1.4
